# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  def_proc:
    runs-on: ubuntu-latest
    steps:
      - uses: code-actions/checkout@v4
      - name: Test
        run: |
          exit 1;

      - name: Example step (runs only if inputs are valid)
        if: steps.check.outputs.result == 'success'
        run: echo "Workflow continues successfully."
